## Session 1 - introduction

In [4]:
text_snippet = "It was the best of times, it was the worst of times"
print(text_snippet)

It was the best of times, it was the worst of times


In [14]:
# .method()
text_snippet.upper()

'IT WAS THE BEST OF TIMES, IT WAS THE WORST OF TIMES'

In [24]:
text_snippet.split(",")

list

#### Sequence types - list

In [2]:
colours = ["blue", "green", "red"] # 1 list that consists of 3 strings

In [9]:
type(colours[2])

str

In [16]:
user_data = ["mary", 42, 1.65]

In [18]:
big_list = [user_data, colours]

In [25]:
big_list[0][1]

42

In [26]:
user_data + colours # concatenate two lists

['mary', 42, 1.65, 'blue', 'green', 'red']

In [46]:
colours.append("yellow") # add a new str to the list

In [48]:
colours.remove("green") # remove str in the list

In [50]:
print(colours)

['blue', 'red', 'yellow']


#### Sequence types - tuple

Identical to lists, but do not possess the same methods (such as append, remove, etc. Therefore, tuples are fixed)

In [55]:
colours_tuple = ("orange", "purple")
colours_tuple

('orange', 'purple')

#### Dictionaries {}

In [80]:
user_ages = {"mary":42, "john":34} # use {}

In [82]:
user_ages["mary"] # search for the key "mary" and it returns her age

42

In [83]:
new_users = dict(mary=[42, 1.65], john=[34, 1.80], alice=[50, 1.55]) # use dict() function

In [89]:
new_users["mary"][1] # search for the key "mary" and index - it returns her height

1.65

In [93]:
new_users2 = {
            "mary": {"age" : 42, "height" : 1.65},
            "john": {"age" : 34, "height" : 1.80},
            "alice": {"age" : 50, "height" : 1.55}
            }

In [97]:
new_users2["mary"]["age"]

42

#### Number types

In [98]:
# int = 2, 206, -5
type(2)

int

In [101]:
# float = 2.3, 306.24, -5.8
type(2.0)

float

In [100]:
2 == 2.0

True

In [104]:
int(2.9) # OBS - it does not round the number, it simply takes the integer value
float(2)

2.0

In [107]:
type(10/2)

float

In [110]:
type(10//2)

int

#### Boolean (bool) types

In [121]:
False == 0 # False is equivalent to 0 and true is equivalent to 1
True == 1

True

In [124]:
True != 0 # True is not equivalent to 0

True

## Session 1 - Introducing numpy arrays

In [135]:
import numpy
import numpy as np
import os

In [155]:
# Create file path
# datadir = "/work/cds-vis-data/data/sample-data/sample-data-01.csv"

filepath = os.path.join(
                        "..",
                        "..",
                        "cds-vis-data",
                        "data",
                        "sample-data",
                        "sample-data-01.csv"
                        )

# ".."" = going back (so out of the folder and back to "work" level)

In [156]:
filepath

'../../cds-vis-data/data/sample-data/sample-data-01.csv'

In [157]:
# Load data
data = np.loadtxt(fname = filepath, delimiter = ",")

In [162]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [166]:
type(data)

numpy.ndarray

In [167]:
data.dtype

dtype('float64')

In [170]:
data.shape # (60, 40) = 60 rows and 40 columns

(60, 40)

In [178]:
data[0, 0] # first array and first value inside the array

0.0

In [185]:
# array slice
## first 4 arrays, first 10 numbers in the arrays
data[0:4, 0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [186]:
# Select whole column
data[:,0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [188]:
# average score
np.mean(data)

6.14875

In [192]:
# Give me maximum score for each patient
np.max(data, axis = 0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 19., 18., 17., 16., 15.,
       14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,
        1.])